const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const ShiftSchema = new Schema({
  employee: { type: Schema.Types.ObjectId, ref: "Employee" },
  startTime: String,
  endTime: String,
  type: {
    type: String,
    enum: ["normal", "congé", "absence", "formation"],
    default: "normal",
  },
});

const DayScheduleSchema = new Schema({
  date: Date,
  shifts: [ShiftSchema],
});

const WeeklyScheduleSchema = new Schema({
  employee: { type: Schema.Types.ObjectId, ref: "Employee", required: true },
  weekStart: Date,
  weekEnd: Date,
  schedules: [DayScheduleSchema],
  isAutoGenerated: { type: Boolean, default: false },
  status: {
    type: String,
    enum: ["brouillon", "publié", "archivé"],
    default: "brouillon",
  },
});

const PlanningSchema = new Schema({
  startDate: Date,
  endDate: Date,
  type: {
    type: String,
    enum: ["jour", "semaine", "mois", "année"],
    required: true,
  },
  weeklySchedules: [WeeklyScheduleSchema],
  constraints: {
    minEmployeesPerShift: Number,
    maxHoursPerWeek: Number,
    preferredShifts: Map,
    unavailableDays: Map,
  },
});

module.exports = mongoose.model("Planning", PlanningSchema);
